/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class stockmarket_Crawler */

#ifndef _Included_stockmarket_Crawler
#define _Included_stockmarket_Crawler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     stockmarket_Crawler
 * Method:    collectData
 * Signature: (Ljava/lang/String;JJ)V
 */
JNIEXPORT void JNICALL Java_stockmarket_Crawler_collectData
  (JNIEnv *, jobject, jstring, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
